name: Monitor Internet

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecutar cada 5 minutos
  workflow_dispatch:  # Para ejecutarlo manualmente si es necesario

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the monitoring script
        run: |
          python monitor.py
